# deployment/ansible/deploy-app.yml
---
- hosts: tag_Purpose_production
  become: yes
  tasks:
    # Docker setup tasks
    - name: Install Docker prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Reset SSH connection to allow user changes to affect current session
      meta: reset_connection

    # Application deployment tasks
    - name: Pull frontend image
      docker_image:
        name: "razielrey/domain-monitor-fe:{{ docker_image_tag }}"
        source: pull
        force_source: yes

    - name: Pull backend image
      docker_image:
        name: "razielrey/domain-monitor-be:{{ docker_image_tag }}"
        source: pull
        force_source: yes

    - name: Start backend container
      docker_container:
        name: be-app
        image: "razielrey/domain-monitor-be:{{ docker_image_tag }}"
        state: started
        network_mode: host
        restart_policy: always

    - name: Start frontend container
      docker_container:
        name: fe-app
        image: "razielrey/domain-monitor-fe:{{ docker_image_tag }}"
        state: started
        network_mode: host
        restart_policy: always
        env:
          BACKEND_URL: "http://localhost:5001"
